version: "3.8"

services:
  web:
    build:
      context: .         # zoekt naar 'Dockerfile' in root
    container_name: solemachina-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
